###-- General --####
set -g prefix C-space						# Set new prefix key
set -g status-position top					# Place Status Bar on Top
set -g set-clipboard on						# Use system clipboard
set -g mouse on								# Enable mouse support
set -g status-interval 2					# Update the status bar every 3 seconds (default: 15 seconds)
set -sg escape-time 0						# Remove key combination delay

####-- Keybinds --####
unbind r
bind r source-file "~/.config/tmux/tmux.conf"	# Reload config from $HOME
# bind r source-file "$HOME/.tmux.conf"			# Best practice
# Split horizontally in CWD
unbind \%
bind \ä split-window -h -c "#{pane_current_path}"
# Split vertically in CWD
unbind \"
bind \ö split-window -v -c "#{pane_current_path}"
# New window in CWD
bind \m new-window -c "#{pane_current_path}"

####-- Appearance --####
# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use vim arrow keys to resize
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

####-- Plugins --####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-cpu'

set -g @vim_navigator_prefix_mapping_clear_screen ""
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha" # latte, frappe, macchiato, or mocha
set -g @catppuccin_window_status_style "basic" # basic, rounded, slanted, custom, or none
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_flags "icon" # none, icon, or text
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
run "~/.config/tmux/plugins/tmux/catppuccin.tmux"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right ""
set -ag status-left "#{E:@catppuccin_status_session}"
# set -ag status-right "#{E:@catppuccin_status_directory}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#[fg=colour245] %H:%M "

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm
