# General
set -g set-clipboard on						# Use system clipboard
set -g mouse on								# Enable mouse support
set -g status-interval 2					# Update the status bar every 3 seconds (default: 15 seconds)
# set -g default-terminal "screen-256color" 	# Set terminal type for 256-color support
# set -ga terminal-overrides ",*256col*:Tc" 	# Override to enable true-color for compatible terminals
# Set prefix key to Ctrl-Space
unbind C-b            		# Unbind the default prefix key
set -g prefix C-space		# Set new prefix key to Ctrl+Space

# Refresh tmux config with r
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Split horizontally in CWD with ä
unbind %
bind ä split-window -h -c "#{pane_current_path}"

# Split vertically in CWD with ö
unbind \"
bind ö split-window -v -c "#{pane_current_path}"

# New window in same path
bind \# new-window -c "#{pane_current_path}"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use vim arrow keys to resize
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-cpu'
# set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'

set -g @vim_navigator_prefix_mapping_clear_screen ""
set -g @resurrect-strategy-nvim 'session'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha" # latte, frappe, macchiato, or mocha
set -g @catppuccin_window_status_style "rounded" # basic, rounded, slanted, custom, or none

# Fix Catppuccin's window fuckery
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"

# Place Status Bar on Top
# set-option -g status-position top

# Catpuccin Status Line
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
# set -ag status-right "#{E:@catppuccin_status_uptime}"
# set -agF status-right "#{E:@catppuccin_status_battery}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm
